[colors]
foreground = "#1b1b1b"
background = "#f2f2f2"
cursor_bg = "#1b1b1b"
cursor_fg = "#f2f2f2"
cursor_border = "#1b1b1b"
selection_fg = "#1b1b1b"
selection_bg = "#d3eef4"

ansi = [
  "#f2f2f2", # black
  "#b61e00", # red
  "#007f4e", # green
  "#b65f00", # yellow
  "#005db1", # blue
  "#bb0055", # magenta
  "#007787", # cyan
  "#1b1b1b", # white
]

brights = [
  "#6e6e6e", # bright black
  "#d02300", # bright red
  "#008e58", # bright green
  "#c96900", # bright yellow
  "#006ed0", # bright blue
  "#cf1f63", # bright magenta
  "#008698", # bright cyan
  "#f2f2f2", # bright white
]

[colors.tab_bar]
background = "#e5e5e5"
inactive_tab_edge = "#e5e5e5"

[colors.tab_bar.active_tab]
bg_color = "#f2f2f2"
fg_color = "#1b1b1b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#e5e5e5"
fg_color = "#555555"
intensity = "Normal"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f2f2f2"
fg_color = "#1b1b1b"

[colors.tab_bar.new_tab]
bg_color = "#e5e5e5"
fg_color = "#555555"

[colors.tab_bar.new_tab_hover]
bg_color = "#f2f2f2"
fg_color = "#1b1b1b"

[metadata]
aliases = []
author = "mjlaufer"
name = "inklight"
